# This is a basic workflow to help you get started with Actions

name: CI - main branch pull request

# Controls when the action will run. 
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache gradle
        uses: actions/cache@v2
        env:
          cache-name: cache-gradle
        with:
          path: ~/.gradle/wrapper/dists
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up JDK11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests, linter and code coverage
        run: ./gradlew check jacocoTestReport

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.0.1
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit the badge (if it changed)
        run: |
          git fetch
          git branch
          git branch -r
          git checkout $GITHUB_HEAD_REF
          GIT_STATUS_PORCELAIN=`git status --porcelain`
          echo "GIT_STATUS_PORCELAIN: $GIT_STATUS_PORCELAIN"

          if [[ $GIT_STATUS_PORCELAIN ]]; then
            git config user.name 'AlexMiroshnikov'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/
          retention-days: 2
